### ISSUE TITLE
Bodleian logo in footer isn't visible in Safari, distorted in FireFox

### ISSUE THREAD

**Issue by kintopp** [culturesofknowledge/emlo#1]
When I view the EMLO site in Safari (v8.07) in the place where the Bodleian library logo should be I just see a blank space. The logo looks fine (though blurry) in Chrome v43 and appears pixelated in FireFox v39 (see screenshot below comparing appearance in Chrome and FireFox).

![screen shot 2015-07-10 at 17 04 32](https://cloud.githubusercontent.com/assets/963588/8622896/bf29de46-2725-11e5-9bf2-8455c05c153c.png)

![screen shot 2015-07-10 at 17 03 56](https://cloud.githubusercontent.com/assets/963588/8622886/a736fe9a-2725-11e5-9191-f615d469e4cb.png)

**Comment by kintopp** [comment]
I think this version should work better. I took it from the digital.bodleian website and inverted it in Illustrator so that it appears black on a white background. It looks fine in Safari, FF and Chrome on a Mac. Didn't test in IE.

https://dl.dropboxusercontent.com/u/1667511/bodleian-footer-logo.svg

**Comment by akademy** [comment]
I've changed the logo - can you check it looks OK in safari?

**Comment by kintopp** [comment]
Close but no cigar.. did you try my attempt above?

![screen shot 2015-07-23 at 16 24 09](https://cloud.githubusercontent.com/assets/963588/8854342/57e69274-3157-11e5-9ed5-e45aa030c870.png)

**Comment by akademy** [comment]
It's fine now
