### ISSUE TITLE
Dates in drop-down menus are awkward to select in Safari and Chrome on OS X 

### ISSUE THREAD

**Issue by kintopp** [culturesofknowledge/emlo#2]
In the current versions of Chrome and Safari on OS X, individual dates are awkward to select in the drop-down menus for the Dates field. This is because (unlike in FireFox) you can view a segment of the drop-down and scroll through that using a scrollbar but need to scroll up and down through the whole, expanded menu (or use the arrow keys).

In addition, in FireFox only, it's possible to start typing the data even with the drop-down menu open. But it's not at all clear to me on what basis this affects what's shown in the date field. I wasn't able to figure out how this worked.

My suggestion: don't use a drop-down menu in the dates field. This is not, except in the strictest sense, a pre-defined list. Just use a regular text field. If someone enters a date that is out of bounds, the search will simply show no letters found.

**Comment by kintopp** [comment]
A possible problem with not using a drop down is indicating "all dates". Perhaps blank (no text) could substitute for this.

**Comment by akademy** [comment]
Added better dropdown select
